version: '3'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.1
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
    environment:
      - GUNICORN_CMD_ARGS=--timeout 300 --workers 1 --worker-class sync
    restart: always
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: insurance-app-streamlit:latest
    ports:
      - "8501:8501"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - mlflow
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 