version: '3'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns --workers 2 --timeout 300
    networks:
      - app-network
    environment:
      - GUNICORN_CMD_ARGS="--timeout 300 --workers 2 --worker-class sync"
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - GIT_PYTHON_REFRESH=quiet
      - PYTHONWARNINGS=ignore::UserWarning
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - mlflow
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 